HotelFazenda_PimIV/HotelFazenda_PimIV/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace HotelFazenda_PimIV.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Lazer()
        {
            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

HotelFazenda_PimIV/HotelFazenda_PimIV/Controllers/HotelController.cs
using Business;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace HotelFazenda_PimIV.Controllers
{
    public class HotelController : Controller
    {
        public ActionResult Consulta()
        {
            ViewBag.Paginas = new Pagina().Lista();
            return View();
        }

        public ActionResult NovoCadastro()
        {
            return View();
        }

        [HttpPost]
        public void CriarCadastro()
        {
            DateTime dataNascimento;
            DateTime.TryParse(Request["datanascimento"], out dataNascimento);
            var pagina = new Pagina();
            pagina.Nome = Request["nome"];
            pagina.CPF = Request["cpf"];
            pagina.Sexo = Request["sexo"];
            pagina.DataNascimento = dataNascimento;
            pagina.PossuiPcD = Request["possuipcd"];
            pagina.CEP = Request["cep"];
            pagina.NumCasa = Request["numcasa"];
            pagina.NumCelular = Request["numcelular"];
            pagina.Email = Request["email"];
            pagina.Save();
            Response.Redirect("/Consulta");
        }

        public ActionResult EditarCadastro(int id)
        {
            var pagina = Pagina.BuscaPorId(id);
            ViewBag.Pagina = pagina;
            return View();
        }

        [HttpPost]
        public void AlterarCadastro(int id)
        {
            try
            {
                var pagina = Pagina.BuscaPorId(id);

                DateTime dataNascimento;
                DateTime.TryParse(Request["datanascimento"], out dataNascimento);

                pagina.Nome = Request["nome"];
                pagina.CPF = Request["cpf"];
                pagina.Sexo = Request["sexo"];
                pagina.DataNascimento = dataNascimento;
                pagina.PossuiPcD = Request["possuipcd"];
                pagina.CEP = Request["cep"];
                pagina.NumCasa = Request["numcasa"];
                pagina.NumCelular = Request["numcelular"];
                pagina.Email = Request["email"];

                pagina.Save();
            }
            catch
            {
                TempData["Sucesso"] = "Página não pode ser alterada";
            }
            Response.Redirect("/Consulta");
        }


        public void ExcluirCadastro(int id)
        {
            Pagina.Excluir(id);
            Response.Redirect("/Consulta");
        }

    }
}

HotelFazenda_PimIV/HotelFazenda_PimIV/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contato";
}
<h2 style="text-align:center;">Contato</h2>

<div class="row">
    <div class="col-sm-6 col-md-8">
            <h3>Envie sua mensagem</h3>
            <div class="row">
                <div class="col-sm-6 col-md-6">
                    <label for="NomeCompleto">Nome completo:</label>
                    <input type="text" class="form-control" placeholder="Insira o nome completo" aria-describedby="sizing-addon2">
                </div>
                <div class="col-sm-6 col-md-6">
                    <label for="TelefoneContato">Telefone para contato:</label>
                    <input type="text" class="form-control" placeholder="Insira o telefone para contato" aria-describedby="sizing-addon2" id="telefone">
                </div>
            </div>
            <br />
            <div class="row">
                <div class="col-sm-6 col-md-6">
                    <label for="EndereçoDeEmail">Email:</label>
                    <input type="email" class="form-control" placeholder="insira o email" aria-describedby="sizing-addon2">
                </div>

                <div class="col-sm-6 col-md-6">
                    <label for="Assunto">Assunto:</label>
                    <input type="text" class="form-control" placeholder="Insira o assunto" aria-describedby="sizing-addon2">
                </div>
            </div>
            <br />
            <div class="row">
                <div class="col-sm-6 col-md-8">
                    <label for="Mensagem">Mensagem:</label>
                    <textarea class="form-control" id="Mensagem" rows="3" placeholder="Insira a mensagem"></textarea>
                </div>
            </div>
            <br />
            <button type="submit" class="btn btn-primary">Enviar</button>
    </div>

    <div class="col-sm-6 col-md-4">
            <h3>Informações para contato</h3>
            <div class="endereco">
                <p>
                    Estrada Municipal, Estr. Pedro Moacir de Almeida
                    <br />
                    Alto da Ponte, São José dos Campos - SP
                    <br />
                    Cep: 79814-185
                </p>
            </div>
            <div class="telefone">
                <p>
                    Telefone: (12) 3456-78-91
                    <br />
                    Whatsapp: (12) 91234-5678
                </p>
            </div>
        </div>
</div>


<!--
    <div class="informacoes">
        <h3>Informações para contato</h3>
        <div class="endereco">
            <p>
                Estrada Municipal, Estr. Pedro Moacir de Almeida
                <br />
                Alto da Ponte, São José dos Campos - SP
                <br />
                Cep: 79814-185
            </p>
        </div>
        <div class="telefone">
            <p>
                Telefone: (12) 3456-78-91
                <br />
                Whatsapp: (12) 91234-5678
            </p>
        </div>
    </div>

    <div class="formulario">
        <h3>Envie sua mensagem</h3>
        <div class="row">
            <div class="col-sm-6 col-md-4">
                <label for="NomeCompleto">Nome completo:</label>
                <input type="text" class="form-control" placeholder="Insira o nome completo" aria-describedby="sizing-addon2">
            </div>
            <div class="col-sm-6 col-md-4">
                <label for="TelefoneContato">Telefone para contato:</label>
                <input type="text" class="form-control" placeholder="Insira o telefone para contato" aria-describedby="sizing-addon2" id="telefone">
            </div>
        </div>
        <br />
        <div class="row">
            <div class="col-sm-6 col-md-4">
                <label for="EndereçoDeEmail">Email:</label>
                <input type="email" class="form-control" placeholder="insira o email" aria-describedby="sizing-addon2">
            </div>

            <div class="col-sm-6 col-md-4">
                <label for="Assunto">Assunto:</label>
                <input type="text" class="form-control" placeholder="Insira o assunto" aria-describedby="sizing-addon2">
            </div>
        </div>
        <br />
        <div class="row">
            <div class="col-sm-6 col-md-4">
                <label for="Mensagem">Mensagem:</label>
                <textarea class="form-control" id="Mensagem" rows="3" placeholder="Insira a mensagem"></textarea>
            </div>
        </div>
        <br />
        <button type="submit" class="btn btn-primary">Enviar</button>
    </div>
    -->

@section Scripts {
    <script>
        $(document).ready(function () {
            $("#telefone").inputmask("mask", { "mask": "(99) 99999-9999" });
            $("#cpf").inputmask("mask", { "mask": "999.999.999-99" }, { reverse: true });
            $("#cep").inputmask("mask", { "mask": "99999-999" });
            $("#nascimento").inputmask("mask", { "mask": "99/99/9999" });
            $("#preco").inputmask("mask", { "mask": "999.999,99" }, { reverse: true });
            $("#valor").inputmask("mask", { "mask": "#.##9,99" }, { reverse: true });
            $("#ip").inputmask("mask", { "mask": "999.999.999.999" });
        });
    </script>
}

HotelFazenda_PimIV/HotelFazenda_PimIV/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home";
}
<h2 style="text-align:center;">Hotel Fazenda</h2>

<div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
    <!-- Indicators -->
    <ol class="carousel-indicators">
        <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
        <li data-target="#carousel-example-generic" data-slide-to="1"></li>
        <li data-target="#carousel-example-generic" data-slide-to="2"></li>
    </ol>

    <!-- Wrapper for slides -->
    <div class="carousel-inner" role="listbox">
        <div class="item active indexImg">
            <img src="~/assets/img/index/img2.jpg" alt="...">
        </div>
        <div class="item indexImg">
            <img src="~/assets/img/index/img3.jpg" alt="...">
        </div>
        <div class="item indexImg">
            <img src="~/assets/img/index/img4.jpg" alt="...">
        </div>
    </div>
</div>

<br />

<h4></h4>
<div class="row">
    <div class="col-sm-6 col-md-4">
        <div class="thumbnail">
            <img src="~/assets/img/index/culinaria.jpg" alt="...">
            <div class="caption">
                <h3>Culinária tipica de fazenda</h3>
                <p>O Hotel Fazenda, apresenta uma culinária tipicamente de fazenda. Em alguns dos pratos servidos durante o almoço e jantar, estão os pastéis de carne e de queijo, o filé grelhado com mexido de queijo, o leitão à pururuca também faz parte das delícias.</p>
            </div>
        </div>
    </div>

    <div class="col-sm-6 col-md-4">
        <div class="thumbnail">
            <img src="~/assets/img/index/petHotelFazenda.jpg" alt="...">
            <div class="caption">
                <h3>Seu pet é bem vindo</h3>
                <p>No Hotel Fazenda você pode trazer seu animal de estimação e dar a ele o que ele mais gosta: a sua companhia</p>
            </div>
        </div>
    </div>

    <div class="col-sm-6 col-md-4">
        <div class="thumbnail">
            <img class="acessibilidadeHotelFazenda" src="~/assets/img/index/acessibilidadeHotel.jpg" alt="...">
            <div class="caption">
                <h3>Hotel com acessibilidade</h3>
                <p>O campo é um hotel com acessibilidade, portanto é um hotel adaptado para receber pessoas com deficiência ou mobilidade reduzida</p>
            </div>
        </div>
    </div>
</div>

HotelFazenda_PimIV/HotelFazenda_PimIV/Views/Home/Lazer.cshtml
@{
    ViewBag.Title = "Lazer";
}

<h2 style="text-align:center;">Lazer</h2>

<div class="row">
    <div class="col-sm-6 col-md-4">
        <div class="thumbnail">
            <img class="ImgLazer" src="~/assets/img/lazer/salaoDeJogos.jpg" title="Salão de Jogos">
            <div class="caption">
                <h3 class="TituloLazer">Salão de Jogos</h3>
            </div>
        </div>
    </div>

    <div class="col-sm-6 col-md-4">
        <div class="thumbnail">
            <img class="ImgLazer" src="~/assets/img/lazer/campoDeFutebol.jpg" title="Campo de Futebol">
            <div class="caption">
                <h3 class="TituloLazer">Campo de Futebol</h3>
            </div>
        </div>
    </div>

    <div class="col-sm-6 col-md-4">
        <div class="thumbnail">
            <img class="ImgLazer" src="~/assets/img/lazer/tirolesa.jpg" title="Campo de Futebol">
            <div class="caption">
                <h3 class="TituloLazer">Tirolesa</h3>
            </div>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-sm-6 col-md-4">
        <div class="thumbnail">
            <img class="ImgLazer" src="~/assets/img/lazer/parquinho.jpg" title="Parquinho">
            <div class="caption">
                <h3 class="TituloLazer">Parqinho</h3>
            </div>
        </div>
    </div>

    <div class="col-sm-6 col-md-4">
        <div class="thumbnail">
            <img class="ImgLazer" src="~/assets/img/lazer/passeioACavalo.jpg" title="Passeio a Cavalo">
            <div class="caption">
                <h3 class="TituloLazer">Passeio a Cavalo</h3>
            </div>
        </div>
    </div>

    <div class="col-sm-6 col-md-4">
        <div class="thumbnail">
            <img class="ImgLazer" src="~/assets/img/lazer/pedalinho.jpg" title="Pedalinho">
            <div class="caption">
                <h3 class="TituloLazer">Pedalinho</h3>
            </div>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-sm-6 col-md-4">
        <div class="thumbnail">
            <img class="ImgLazer" src="~/assets/img/lazer/piscina.jpg" title="Piscina">
            <div class="caption">
                <h3 class="TituloLazer">Piscina</h3>
            </div>
        </div>
    </div>

    <div class="col-sm-6 col-md-4">
        <div class="thumbnail">
            <img class="ImgLazer" src="~/assets/img/lazer/quadraPoliesportiva.jpg" title="Quadra Poliesportiva">
            <div class="caption">
                <h3 class="TituloLazer">Quadra Poliesportiva</h3>
            </div>
        </div>
    </div>

    <div class="col-sm-6 col-md-4">
        <div class="thumbnail">
            <img class="ImgLazer" src="~/assets/img/lazer/bocha.jpg" title="Bocha">
            <div class="caption">
                <h3 class="TituloLazer">Bocha</h3>
            </div>
        </div>
    </div>
</div>

HotelFazenda_PimIV/HotelFazenda_PimIV/Views/Hotel/AlterarCadastro.cshtml
@{
    ViewBag.Title = "AterarCadastro";
}

<h2>AterarCadastro</h2>

HotelFazenda_PimIV/HotelFazenda_PimIV/Views/Hotel/Consulta.cshtml
@{
    ViewBag.Title = "Consulta";
    List<Business.Pagina> paginas = ViewBag.Paginas;
}

@if (TempData["Sucesso"] != null)
{
    <div class="alert alert-success">@TempData["Sucesso"]</div>
}
@if (TempData["Erro"] != null)
{
    <div class="alert alert-danger">@TempData["Erro"]</div>
}

<h2>Consulta de Hospede</h2>

<div class="jumbotron">
    <div>
        <a href="/Consulta/NovoCadastro" class="btn btn-default">Novo cadastro</a>
    </div>
    <table class="table table-condensed">
        <tr>
            <td>Nome</td>
            <td>Data de nascimento</td>
            <td>Sexo</td>
            <td>Possui PcD</td>
            <td>Num Celular</td>
            <td>E-mail</td>
            <td></td>
            <td></td>
        </tr>
        @foreach (var p in paginas)
        {
            <tr>
                <td>@p.Nome</td>
                <td>@p.DataNascimento.ToString("MM/dd/yyyy")</td>
                <td>@p.Sexo</td>
                <td>@p.PossuiPcD</td>
                <td>@p.NumCelular</td>
                <td>@p.Email</td>
                <td><a href="/Consulta/@p.Id/EditarCadastro" class="btn btn-primary">Atualizar</a></td>
                <td><a href="/Consulta/@p.Id/ExcluirCadastro" class="btn btn-danger" onclick="ValidarExclusao(@p.Id, evento)">Excluir</a></td>
            </tr>
        }
    </table>
</div>

HotelFazenda_PimIV/HotelFazenda_PimIV/Views/Hotel/CriarCadastro.cshtml
@{
    ViewBag.Title = "CriarCadastro";
}

<h2>CriarCadastro</h2>

HotelFazenda_PimIV/HotelFazenda_PimIV/Views/Hotel/EditarCadastro.cshtml
@{
    ViewBag.Title = "Editar Cadastro";
    Business.Pagina pagina = ViewBag.Pagina;
}

<h2>Editar Cadastro</h2>

<div>
    <a href="/Consulta" class="btn btn-primary">Voltar</a>
</div>
<br />

<form action="/Consulta/@pagina.Id/AlterarCadastro" method="post">
    <div class="row">
        <div class="col-sm-6 col-md-4">
            <label for="CPF">CPF:</label>
            <input type="text" class="form-control" id="cpf" name="CPF" value="@pagina.CPF" />
        </div>

        <div class="col-sm-6 col-md-4">
            <label for="nome">Nome Completo:</label>
            <input type="text" class="form-control" id="nome" name="nome" value="@pagina.Nome" />
        </div>

        <div class="col-sm-6 col-md-4">
            <label for="DataNascimento">Data de Nascimento:</label>
            <input type="text" class="form-control" id="nascimento" name="DataNascimento" value="@pagina.DataNascimento" />
        </div>
    </div>
    <br />
    <div class="row">
        <div class="col-sm-6 col-md-4">
            <label for="Sexo">Sexo:</label>
            <input type="text" class="form-control" id="Sexo" name="Sexo" value="@pagina.Sexo" />
        </div>

        <div class="col-sm-6 col-md-4">
            <label for="PossuiPcD">Possui PcD:</label>
            <input type="text" class="form-control" id="PossuiPcD" name="PossuiPcD" value="@pagina.PossuiPcD" />
        </div>

        <div class="col-sm-6 col-md-4">
            <label for="NumCelular">Número de celular:</label>
            <input type="text" class="form-control" id="telefone" name="NumCelular" value="@pagina.NumCelular" />
        </div>
    </div>
    <br />
    <div class="row">
        <div class="col-sm-6 col-md-4">
            <label for="Email">Email:</label>
            <input type="email" class="form-control" id="Email" name="Email" value="@pagina.Email" />
        </div>
        <br />
        <div class="col-sm-6 col-md-4">
            <label for="CEP">CEP:</label>
            <input type="text" class="form-control" id="cep" name="CEP" value="@pagina.CEP" />
        </div>

        <div class="col-sm-6 col-md-4">
            <label for="NumCasa">Número da casa:</label>
            <input type="text" class="form-control" id="NumCasa" name="NumCasa" value="@pagina.NumCasa" />
        </div>
    </div>
    <button type="submit" class="btn btn-primary">Atualizar</button>
</form>

@section Scripts {
    <script>
        $(document).ready(function () {
            $("#telefone").inputmask("mask", { "mask": "(99) 99999-9999" });
            $("#cpf").inputmask("mask", { "mask": "999.999.999-99" }, { reverse: true });
            $("#cep").inputmask("mask", { "mask": "99999-999" });
            $("#nascimento").inputmask("mask", { "mask": "99/99/9999" });
        });
    </script>
}

HotelFazenda_PimIV/HotelFazenda_PimIV/Views/Hotel/NovoCadastro.cshtml
@{
    ViewBag.Title = "Novo Cadastro";
}

<h2>Novo Cadastro</h2>


<div>
    <a href="/Consulta" class="btn btn-primary">Voltar</a>
</div>
<br />

<form action="/Consulta/CriarCadastro" method="post">
    <div class="row">
        <div class="col-sm-6 col-md-4">
            <label for="CPF">CPF:</label>
            <input type="text" class="form-control" id="cpf" name="CPF" />
        </div>

        <div class="col-sm-6 col-md-4">
            <label for="nome">Nome Completo:</label>
            <input type="text" class="form-control" id="nome" name="nome" />
        </div>

        <div class="col-sm-6 col-md-4">
            <label for="DataNascimento">Data de Nascimento:</label>
            <input type="text" class="form-control" id="nascimento" name="DataNascimento" />
        </div>
    </div>
    <br />
    <div class="row">
        <div class="col-sm-6 col-md-4">
            <label for="Sexo">Sexo:</label>
            <input type="text" class="form-control" id="Sexo" name="Sexo" />
        </div>

        <div class="col-sm-6 col-md-4">
            <label for="PossuiPcD">Possui PcD:</label>
            <input type="text" class="form-control" id="PossuiPcD" name="PossuiPcD" />
        </div>

        <div class="col-sm-6 col-md-4">
            <label for="NumCelular">Número de celular:</label>
            <input type="text" class="form-control" id="telefone" name="NumCelular" />
        </div>
    </div>
    <br />
    <div class="row">
        <div class="col-sm-6 col-md-4">
            <label for="Email">Email:</label>
            <input type="email" class="form-control" id="Email" name="Email" />
        </div>
        <br />
        <div class="col-sm-6 col-md-4">
            <label for="CEP">CEP:</label>
            <input type="text" class="form-control" id="cep" name="CEP" />
        </div>

        <div class="col-sm-6 col-md-4">
            <label for="NumCasa">Número da casa:</label>
            <input type="text" class="form-control" id="NumCasa" name="NumCasa" />
        </div>
    </div>
    <button type="submit" class="btn btn-primary">Cadastrar</button>
</form>

    @section Scripts {
        <script>
            $(document).ready(function () {
                $("#telefone").inputmask("mask", { "mask": "(99) 99999-9999" });
                $("#cpf").inputmask("mask", { "mask": "999.999.999-99" }, { reverse: true });
                $("#cep").inputmask("mask", { "mask": "99999-999" });
                $("#nascimento").inputmask("mask", { "mask": "99/99/9999" });
            });
        </script>
    }

HotelFazenda_PimIV/HotelFazenda_PimIV/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Hotel Fazenda</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/Scripts/validacoes.js")
    @Styles.Render("~/assets/img/")
    @Styles.Render("~/assets/style.css")
</head>
<body>
    <div class="navbar navbar-default  navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Hotel Fazenda", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse navbar-right">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("Lazer", "Lazer", "Home")</li>
                    <li>@Html.ActionLink("Contato", "Contact", "Home")</li>
                    <li>@Html.ActionLink("Consulta", "Consulta", "Hotel")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Hotel Fazenda</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/inputmask")
    @RenderSection("scripts", required: false)
</body>
</html>